version: '3.1'

services:
  mongo:
    image: mongo:4.2-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    volumes:
      - /home/shyeon/workspace/de/mongo-with-fastapi/data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOUSER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGOUSER}:${PASSWORD}@mongo:27017/
    depends_on:
      - mongo
